import { Badge } from "@/components/ui/badge";
import { Building2, Sparkles, Globe, GraduationCap, BookOpen, Layers } from "lucide-react";
import { cn } from "@/lib/utils";

export type ContentSource = 
  | 'database'           // From community_syllabi cache
  | 'tier1_academic'     // Fresh from MIT/Yale/etc.
  | 'tier2_aggregated'   // Fresh from Coursera/edX aggregation
  | 'tier3_ai_generated' // AI-generated fallback
  | 'ai_augmented'       // Database + AI augmentation
  | 'web_sourced';       // Ad-hoc topic

interface ProvenanceBadgeProps {
  source: ContentSource;
  className?: string;
  showLabel?: boolean;
  size?: 'sm' | 'md' | 'lg';
}

const sourceConfig: Record<ContentSource, {
  icon: typeof Building2;
  label: string;
  shortLabel: string;
  description: string;
  variant: 'default' | 'secondary' | 'outline' | 'destructive';
  className: string;
}> = {
  database: {
    icon: Building2,
    label: 'Curated Academic Syllabus',
    shortLabel: 'Academic',
    description: 'From our curated database of academic syllabi',
    variant: 'default',
    className: 'bg-emerald-500/10 text-emerald-700 dark:text-emerald-400 border-emerald-500/30 hover:bg-emerald-500/20'
  },
  tier1_academic: {
    icon: GraduationCap,
    label: 'University Syllabus',
    shortLabel: 'University',
    description: 'Sourced from MIT, Yale, Harvard, and other top universities',
    variant: 'default',
    className: 'bg-blue-500/10 text-blue-700 dark:text-blue-400 border-blue-500/30 hover:bg-blue-500/20'
  },
  tier2_aggregated: {
    icon: BookOpen,
    label: 'Aggregated from MOOCs',
    shortLabel: 'MOOC',
    description: 'Compiled from Coursera, edX, and other online platforms',
    variant: 'secondary',
    className: 'bg-violet-500/10 text-violet-700 dark:text-violet-400 border-violet-500/30 hover:bg-violet-500/20'
  },
  tier3_ai_generated: {
    icon: Sparkles,
    label: 'AI-Generated Curriculum',
    shortLabel: 'AI Generated',
    description: 'Generated by AI when no academic sources were found',
    variant: 'outline',
    className: 'bg-amber-500/10 text-amber-700 dark:text-amber-400 border-amber-500/30 hover:bg-amber-500/20'
  },
  ai_augmented: {
    icon: Layers,
    label: 'AI-Augmented Academic Syllabus',
    shortLabel: 'AI Augmented',
    description: 'Academic syllabus enhanced with AI-discovered content',
    variant: 'default',
    className: 'bg-gradient-to-r from-emerald-500/10 to-violet-500/10 text-violet-700 dark:text-violet-400 border-violet-500/30 hover:from-emerald-500/20 hover:to-violet-500/20'
  },
  web_sourced: {
    icon: Globe,
    label: 'Web-Sourced Curriculum',
    shortLabel: 'Web Sourced',
    description: 'Generated from web sources for this custom topic',
    variant: 'outline',
    className: 'bg-orange-500/10 text-orange-700 dark:text-orange-400 border-orange-500/30 hover:bg-orange-500/20'
  }
};

export function ProvenanceBadge({ source, className, showLabel = true, size = 'md' }: ProvenanceBadgeProps) {
  const config = sourceConfig[source];
  const Icon = config.icon;
  
  const sizeClasses = {
    sm: 'text-xs px-2 py-0.5',
    md: 'text-sm px-3 py-1',
    lg: 'text-base px-4 py-1.5'
  };
  
  const iconSizes = {
    sm: 'h-3 w-3',
    md: 'h-4 w-4',
    lg: 'h-5 w-5'
  };

  return (
    <Badge 
      variant="outline" 
      className={cn(
        'font-medium border transition-colors cursor-default',
        sizeClasses[size],
        config.className,
        className
      )}
      title={config.description}
    >
      <Icon className={cn(iconSizes[size], showLabel && 'mr-1.5')} />
      {showLabel && (size === 'sm' ? config.shortLabel : config.label)}
    </Badge>
  );
}

// Helper function to determine content source from syllabus data
export function determineContentSource(syllabusData: {
  fromCache?: boolean;
  isAdHoc?: boolean;
  isAIEnhanced?: boolean;
  source?: string;
}): ContentSource {
  // Ad-hoc topics are always web-sourced
  if (syllabusData.isAdHoc) {
    return 'web_sourced';
  }
  
  // AI-enhanced mode
  if (syllabusData.isAIEnhanced) {
    return 'ai_augmented';
  }
  
  // From cache = database
  if (syllabusData.fromCache) {
    return 'database';
  }
  
  // Parse source string to determine tier
  const source = syllabusData.source?.toLowerCase() || '';
  
  if (source.includes('mit') || source.includes('yale') || source.includes('harvard') || 
      source.includes('stanford') || source.includes('university') || source.includes('college') ||
      source.includes('tier 1') || source.includes('authoritative')) {
    return 'tier1_academic';
  }
  
  if (source.includes('coursera') || source.includes('edx') || source.includes('aggregated') ||
      source.includes('mooc') || source.includes('merged') || source.includes('tier 2')) {
    return 'tier2_aggregated';
  }
  
  if (source.includes('ai') || source.includes('generated') || source.includes('backward design') ||
      source.includes('tier 3')) {
    return 'tier3_ai_generated';
  }
  
  // Default to database if we can't determine
  return 'database';
}

// Disclaimer component for AI-generated content
interface ProvenanceDisclaimerProps {
  source: ContentSource;
  className?: string;
}

export function ProvenanceDisclaimer({ source, className }: ProvenanceDisclaimerProps) {
  if (source === 'database' || source === 'tier1_academic') {
    return null; // No disclaimer needed for academic sources
  }
  
  const disclaimers: Partial<Record<ContentSource, string>> = {
    tier3_ai_generated: "We couldn't find an existing academic syllabus for this topic. The curriculum below was generated using AI based on pedagogical best practices.",
    web_sourced: "This is a custom topic not found in our academic database. The curriculum was generated using AI and web sources.",
    ai_augmented: "This academic syllabus has been enhanced with AI-discovered content and industry sources.",
    tier2_aggregated: "This curriculum was compiled from multiple online learning platforms."
  };
  
  const message = disclaimers[source];
  if (!message) return null;
  
  const isWarning = source === 'tier3_ai_generated' || source === 'web_sourced';
  
  return (
    <div className={cn(
      'flex items-start gap-3 p-4 rounded-lg border text-sm',
      isWarning 
        ? 'bg-amber-500/5 border-amber-500/20 text-amber-700 dark:text-amber-400'
        : 'bg-muted/50 border-border text-muted-foreground',
      className
    )}>
      <Sparkles className="h-4 w-4 mt-0.5 flex-shrink-0" />
      <p>{message}</p>
    </div>
  );
}
